/**
 * SpecForge - Curated Architecture Presets
 * Pre-configured targets defined in Section 18 of the specification
 */

import { ProjectSpecification } from '../core';

export interface ArchitecturePreset {
  id: string;
  name: string;
  tagline: string;
  description: string;
  badge: string;
  category: 'fullstack' | 'desktop' | 'backend' | 'frontend';
  spec: ProjectSpecification;
}

export const PRESETS: ArchitecturePreset[] = [
  {
    id: 'rust-react-sqlite',
    name: 'Rust + React + SQLite',
    tagline: 'Fullstack Moderne & Autonome',
    description: 'Architecture complète, ultra-rapide et autonome avec serveur Axum, interface React 19 et base de données embarquée SQLite.',
    badge: 'Recommandé',
    category: 'fullstack',
    spec: {
      specVersion: '1.0.0',
      project: {
        name: 'Lexi Core',
        slug: 'lexi-core',
        description: 'Plateforme fullstack haute performance avec Axum et React 19.',
        type: 'fullstack',
        version: '0.1.0',
        author: 'SpecForge Builder',
        license: 'MIT',
      },
      backend: {
        enabled: true,
        language: 'rust',
        framework: 'axum',
        port: 8080,
        logging: true,
        cors: true,
      },
      frontend: {
        enabled: true,
        framework: 'react',
        bundler: 'vite',
        language: 'typescript',
        styling: 'tailwind',
        tauri: false,
      },
      database: {
        enabled: true,
        type: 'sqlite',
        orm: 'sqlx',
        migrations: true,
        pooling: true,
      },
      api: {
        style: 'rest',
        auth: true,
        openapi: true,
        rateLimiting: false,
      },
      authentication: {
        enabled: true,
        provider: 'jwt',
        sessionStore: false,
      },
      infrastructure: {
        docker: true,
        compose: false,
        systemd: true,
        vpsScript: false,
        nginx: false,
      },
      quality: {
        tests: true,
        lint: true,
        ci: true,
        gitHooks: true,
      },
      documentation: {
        readme: true,
        architectureDoc: true,
        installDoc: true,
        decisionsLog: true,
      },
    },
  },
  {
    id: 'rust-react-postgres',
    name: 'Rust + React + PostgreSQL',
    tagline: 'Fullstack Cloud Scalable',
    description: 'Pile haute charge prête pour la production avec base PostgreSQL conteneurisée sous Docker Compose.',
    badge: 'Enterprise',
    category: 'fullstack',
    spec: {
      specVersion: '1.0.0',
      project: {
        name: 'Enterprise Hub',
        slug: 'enterprise-hub',
        description: 'Système cloud distribué avec Rust Axum, PostgreSQL et React.',
        type: 'fullstack',
        version: '0.1.0',
        author: 'SpecForge Builder',
        license: 'MIT',
      },
      backend: {
        enabled: true,
        language: 'rust',
        framework: 'axum',
        port: 8080,
        logging: true,
        cors: true,
      },
      frontend: {
        enabled: true,
        framework: 'react',
        bundler: 'vite',
        language: 'typescript',
        styling: 'tailwind',
        tauri: false,
      },
      database: {
        enabled: true,
        type: 'postgresql',
        orm: 'sqlx',
        migrations: true,
        pooling: true,
      },
      api: {
        style: 'rest',
        auth: true,
        openapi: true,
        rateLimiting: true,
      },
      authentication: {
        enabled: true,
        provider: 'jwt',
        sessionStore: false,
      },
      infrastructure: {
        docker: true,
        compose: true,
        systemd: false,
        vpsScript: false,
        nginx: true,
      },
      quality: {
        tests: true,
        lint: true,
        ci: true,
        gitHooks: true,
      },
      documentation: {
        readme: true,
        architectureDoc: true,
        installDoc: true,
        decisionsLog: true,
      },
    },
  },
  {
    id: 'rust-tauri-react',
    name: 'Rust + Tauri + React',
    tagline: 'Application Bureau Légère',
    description: 'Application de bureau native pour macOS, Windows et Linux avec backend Rust natif, interface web React et SQLite local.',
    badge: 'Desktop',
    category: 'desktop',
    spec: {
      specVersion: '1.0.0',
      project: {
        name: 'OmniDesktop',
        slug: 'omni-desktop',
        description: 'Logiciel de bureau natif fluide avec Tauri et SQLite.',
        type: 'desktop',
        version: '0.1.0',
        author: 'SpecForge Builder',
        license: 'MIT',
      },
      backend: {
        enabled: false,
        language: 'rust',
        framework: 'axum',
        port: 8080,
        logging: true,
        cors: false,
      },
      frontend: {
        enabled: true,
        framework: 'react',
        bundler: 'vite',
        language: 'typescript',
        styling: 'tailwind',
        tauri: true,
      },
      database: {
        enabled: true,
        type: 'sqlite',
        orm: 'sqlx',
        migrations: true,
        pooling: false,
      },
      api: {
        style: 'none',
        auth: false,
        openapi: false,
        rateLimiting: false,
      },
      authentication: {
        enabled: false,
        provider: 'none',
        sessionStore: false,
      },
      infrastructure: {
        docker: false,
        compose: false,
        systemd: false,
        vpsScript: false,
        nginx: false,
      },
      quality: {
        tests: true,
        lint: true,
        ci: true,
        gitHooks: false,
      },
      documentation: {
        readme: true,
        architectureDoc: true,
        installDoc: true,
        decisionsLog: true,
      },
    },
  },
  {
    id: 'rust-backend-only',
    name: 'Rust Backend Only',
    tagline: 'Microservice Haute Performance',
    description: 'Microservice API REST pur en Rust sans couche frontend. Temps de réponse en microsecondes et empreinte mémoire négligeable.',
    badge: 'API / Microservice',
    category: 'backend',
    spec: {
      specVersion: '1.0.0',
      project: {
        name: 'FastMicro',
        slug: 'fast-micro',
        description: 'Microservice API REST ultra-rapide en Rust Axum.',
        type: 'backend-only',
        version: '0.1.0',
        author: 'SpecForge Builder',
        license: 'Apache-2.0',
      },
      backend: {
        enabled: true,
        language: 'rust',
        framework: 'axum',
        port: 8080,
        logging: true,
        cors: true,
      },
      frontend: {
        enabled: false,
        framework: 'none',
        bundler: 'vite',
        language: 'typescript',
        styling: 'tailwind',
        tauri: false,
      },
      database: {
        enabled: true,
        type: 'sqlite',
        orm: 'sqlx',
        migrations: true,
        pooling: true,
      },
      api: {
        style: 'rest',
        auth: true,
        openapi: true,
        rateLimiting: true,
      },
      authentication: {
        enabled: true,
        provider: 'jwt',
        sessionStore: false,
      },
      infrastructure: {
        docker: true,
        compose: false,
        systemd: true,
        vpsScript: true,
        nginx: false,
      },
      quality: {
        tests: true,
        lint: true,
        ci: true,
        gitHooks: true,
      },
      documentation: {
        readme: true,
        architectureDoc: true,
        installDoc: true,
        decisionsLog: true,
      },
    },
  },
  {
    id: 'react-frontend-only',
    name: 'React Frontend Only',
    tagline: 'Application SPA Client-Side',
    description: 'Application frontend autonome sous React 19 et Vite avec Tailwind CSS, prête à consommer des APIs externes ou un BaaS.',
    badge: 'Client SPA',
    category: 'frontend',
    spec: {
      specVersion: '1.0.0',
      project: {
        name: 'GlassApp',
        slug: 'glass-app',
        description: 'Single-Page Application réactive avec React 19 et Tailwind CSS.',
        type: 'frontend-only',
        version: '0.1.0',
        author: 'SpecForge Builder',
        license: 'MIT',
      },
      backend: {
        enabled: false,
        language: 'rust',
        framework: 'axum',
        port: 8080,
        logging: false,
        cors: false,
      },
      frontend: {
        enabled: true,
        framework: 'react',
        bundler: 'vite',
        language: 'typescript',
        styling: 'tailwind',
        tauri: false,
      },
      database: {
        enabled: false,
        type: 'none',
        orm: 'sqlx',
        migrations: false,
        pooling: false,
      },
      api: {
        style: 'none',
        auth: false,
        openapi: false,
        rateLimiting: false,
      },
      authentication: {
        enabled: false,
        provider: 'none',
        sessionStore: false,
      },
      infrastructure: {
        docker: true,
        compose: false,
        systemd: false,
        vpsScript: false,
        nginx: true,
      },
      quality: {
        tests: true,
        lint: true,
        ci: true,
        gitHooks: true,
      },
      documentation: {
        readme: true,
        architectureDoc: true,
        installDoc: true,
        decisionsLog: false,
      },
    },
  },
];
